push = require 'lib/push'
Class = require 'lib/class'

require 'src/StateMachine'
require 'src/Constants'
require 'src/Util'

require 'src/Player'
require 'src/star'
require 'src/Brick'
require 'src/RainbowStar'

require 'src/states/BaseState'
require 'src/states/StartMenuState'
require 'src/states/ServeState'
require 'src/states/HighscoreState'
require 'src/states/SkinState'
require 'src/states/PlayState'
require 'src/states/LoseState'
require 'src/states/WinState'
require 'src/states/EnterHighscoreState'